### ISSUE TITLE
npc上线server报错

### ISSUE THREAD

**Issue by noobevilc** [YDHCUI/manjusaka#14]
当有新的肉鸡上线时 server端报错

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xae0429]

goroutine 30 [running]:
nps/controller.WebHook(0xc000092300)
	/root/src/NPSC2/nps/controller/npc.go:318 +0x429
created by nps/controller.AgentController
	/root/src/NPSC2/nps/controller/npc.go:208 +0xaa5
````

**Comment by YDHCUI** [comment]
看着是上线提醒的地方报错了，是不是上线提醒配置写错了？

**Comment by YDHCUI** [comment]
conf.toml 里面修改webhook项  改完需要重启应用
